export const GET_ASTEROID_INFO = "GET_ASTEROID_INFO";
export const GET_ASTEROID_INFO_FAIL = "GET_ASTEROID_INFO_FAIL";
export const RESET_ASTEROID_INFO = "RESET_ASTEROID_INFO";

export const GET_ASTEROID_IDS = "GET_ASTEROID_IDS";
export const GET_ASTEROID_IDS_FAIL = "GET_ASTEROID_IDS_FAIL";
export const RESET_ASTEROID_IDS = "RESET_ASTEROID_IDS";
